easy_admin:
    entities:
        Category:
            class: AppBundle\Entity\Category

        Wallpaper:
            class: AppBundle\Entity\Wallpaper
            list:
                fields:
                    - 'id'
                    - 'filename'
                    - 'slug'
                    - { property: 'width', format: '%d' }
                    - { property: 'height', format: '%d' }
                    - 'category'
                    - { property: 'image', type: 'image', base_path: '/images/' }
            form:
                fields:
                    - { property: "file", type: "file", label: "Images" }
                    - 'slug'
                    - 'category'