easy_admin:
    entities:
        Category:
            class: AppBundle\Entity\Category
            list:
                fields:
                    - 'name'

        Wallpaper:
            class: AppBundle\Entity\Wallpaper
            list:
                fields:
                    - 'id'
                    - 'filename'
                    - 'slug'
                    - { property: 'width', format: '%d' }
                    - { property: 'height', format: '%d' }
                    - 'category'
                    - { property: 'image', type: 'image', base_path: '/images/' }
            form:
                fields:
                    - { property: "file", type: 'AppBundle\Form\Type\UploadedFileType', type_options: { required: true } }
                    - 'slug'
                    - 'category'